version: '3.7'

services:
  db:
    container_name: "test_db"
    platform: linux/x86_64
    image: mysql:8.0.2
    environment:
      MYSQL_ROOT_PASSWORD: "104725"
      MYSQL_DATABASE: "MENU"
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always
    command: --default-authentication-plugin=mysql_native_password

  api:
    container_name: "test_api"
    build:
      context: .
      dockerfile: api.Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      DATABASE_USER: root
      DATABASE_PASSWORD: 104725
      DATABASE_NAME: MENU
    command: >
      sh -c "wait-for ${DATABASE_HOST}:${DATABASE_PORT} -- \
      CompileDaemon --build='go build -o main main.go' \
      --command=./main"

volumes:
  mysql_data:
